// ============================================================================
// kSlaveTypes.cpp — Auto-generated slave type definitions.
// Generated by scripts/parse_esi.py from ESI XML files.
// Placeholder for Phase 1 — will be populated when ESI files are added.
// ============================================================================

namespace fc::ethercat {

// Auto-generated content will be placed here.

} // namespace fc::ethercat
